module.exports = {
  apps: [
    {
      name: 'pos-backend',
      script: 'index.mjs',
      cwd: '/home/opc/pos-backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '300M',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        TIMEZONE: 'Asia/Karachi',
        MONGODB_URI: '',
        JWT_PUBLIC_KEY_PATH: './public.key',
        JWT_ACCESS_TOKEN_EXPIRY: '8h',
        CORS_ORIGINS: '*',
        RATE_LIMIT_WINDOW_MS: 900000,
        RATE_LIMIT_MAX: 100,
        AUTH_RATE_LIMIT_MAX: 10,
        BODY_SIZE_LIMIT: '1mb',
        CLOUDINARY_CLOUD_NAME: '',
        CLOUDINARY_API_KEY: '',
        CLOUDINARY_API_SECRET: '',
        NODEMAILER_EMAIL: '',
        NODEMAILER_PASS: '',
      },
    },
  ],
};
